package dolaa;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class SignUp extends javax.swing.JFrame {
    String gen = "female";
    
    
    ImageIcon img =new ImageIcon("C:\\Users\\moham\\Downloads\\form.png");
    public SignUp() {
        initComponents();
    
        setLocationRelativeTo(null);
        setIconImage(img.getImage());  
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        pass2 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lName = new javax.swing.JTextField();
        pass = new javax.swing.JLabel();
        Password = new javax.swing.JPasswordField();
        pass1 = new javax.swing.JLabel();
        sendBut = new javax.swing.JButton();
        fName = new javax.swing.JTextField();
        Email = new javax.swing.JTextField();
        emptyy = new javax.swing.JLabel();
        jRadioButton2 = new javax.swing.JRadioButton();
        Gender = new javax.swing.JLabel();
        jRadioButton3 = new javax.swing.JRadioButton();
        Countrylable = new javax.swing.JLabel();
        Country = new javax.swing.JComboBox<>();
        SecQlable = new javax.swing.JLabel();
        SecQ = new javax.swing.JComboBox<>();
        Birthlable = new javax.swing.JLabel();
        SecQ2 = new javax.swing.JTextField();
        Birth1 = new com.toedter.calendar.JDateChooser();

        jLabel5.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Last Name:");

        pass2.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        pass2.setForeground(new java.awt.Color(0, 0, 0));
        pass2.setText("Email:");
        pass2.setToolTipText("Write your password");

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Registration");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                close(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 500));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 550));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(102, 0, 102));
        jPanel2.setForeground(new java.awt.Color(204, 204, 204));
        jPanel2.setPreferredSize(new java.awt.Dimension(400, 500));

        jLabel6.setFont(new java.awt.Font("Dialog", 3, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Mohamed Adel 20200233");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(jLabel6))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jLabel7)))
                .addContainerGap(127, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 173, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap())
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 400, 500);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setMaximumSize(new java.awt.Dimension(400, 510));
        jPanel3.setMinimumSize(new java.awt.Dimension(400, 500));
        jPanel3.setName(""); // NOI18N
        jPanel3.setPreferredSize(new java.awt.Dimension(400, 500));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Sign Up Form");
        jLabel1.setToolTipText("");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("First Name:");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Last Name:");

        lName.setBackground(new java.awt.Color(255, 255, 255));
        lName.setForeground(new java.awt.Color(0, 0, 0));
        lName.setToolTipText("Write your last name");

        pass.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        pass.setForeground(new java.awt.Color(0, 0, 0));
        pass.setText("Email:");
        pass.setToolTipText("Write your password");

        Password.setBackground(new java.awt.Color(255, 255, 255));
        Password.setForeground(new java.awt.Color(0, 0, 0));
        Password.setToolTipText("Write your password");

        pass1.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        pass1.setForeground(new java.awt.Color(0, 0, 0));
        pass1.setText("Password:");
        pass1.setToolTipText("Write your password");

        sendBut.setBackground(new java.awt.Color(204, 204, 204));
        sendBut.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        sendBut.setForeground(new java.awt.Color(0, 0, 0));
        sendBut.setText("Register");
        sendBut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sendBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hover(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                notHover(evt);
            }
        });
        sendBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendButActionPerformed(evt);
            }
        });

        fName.setBackground(new java.awt.Color(255, 255, 255));
        fName.setForeground(new java.awt.Color(0, 0, 0));
        fName.setToolTipText("Write your last name");

        Email.setBackground(new java.awt.Color(255, 255, 255));
        Email.setForeground(new java.awt.Color(0, 0, 0));
        Email.setToolTipText("Write your last name");

        jRadioButton2.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(0, 0, 0));
        jRadioButton2.setSelected(true);
        jRadioButton2.setText("Female");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        Gender.setBackground(new java.awt.Color(255, 255, 255));
        Gender.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        Gender.setForeground(new java.awt.Color(0, 0, 0));
        Gender.setText("Gender:");
        Gender.setToolTipText("");

        jRadioButton3.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jRadioButton3.setForeground(new java.awt.Color(0, 0, 0));
        jRadioButton3.setText("Male");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        Countrylable.setBackground(new java.awt.Color(255, 255, 255));
        Countrylable.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        Countrylable.setForeground(new java.awt.Color(0, 0, 0));
        Countrylable.setText("Country:");
        Countrylable.setToolTipText("");

        Country.setBackground(new java.awt.Color(255, 255, 255));
        Country.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        Country.setForeground(new java.awt.Color(0, 0, 0));
        Country.setMaximumRowCount(9);
        Country.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Select-", "Egypt", "Oman", "USA", "Canada", "Germany", "France", "Italy", "Qatar" }));
        Country.setToolTipText("");
        Country.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CountryActionPerformed(evt);
            }
        });

        SecQlable.setBackground(new java.awt.Color(255, 255, 255));
        SecQlable.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        SecQlable.setForeground(new java.awt.Color(0, 0, 0));
        SecQlable.setText("Secret Question:");
        SecQlable.setToolTipText("");

        SecQ.setBackground(new java.awt.Color(255, 255, 255));
        SecQ.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        SecQ.setForeground(new java.awt.Color(0, 0, 0));
        SecQ.setMaximumRowCount(9);
        SecQ.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Select-", "What was your childhood nickname?", "What is the name of your favorite childhood friend?", "What street did you live on in third grade?", "What is your oldest sibling's middle name?", "What school did you attend for sixth grade?", "What was the name of your first stuffed animal?", "In what city or town did your mother and father meet?", "What is the name of a college you applied to but didn't attend?" }));
        SecQ.setToolTipText("");
        SecQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SecQActionPerformed(evt);
            }
        });

        Birthlable.setBackground(new java.awt.Color(255, 255, 255));
        Birthlable.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        Birthlable.setForeground(new java.awt.Color(0, 0, 0));
        Birthlable.setText("Date of Birth:");
        Birthlable.setToolTipText("");

        SecQ2.setBackground(new java.awt.Color(255, 255, 255));
        SecQ2.setForeground(new java.awt.Color(0, 0, 0));
        SecQ2.setToolTipText("Write your last name");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(SecQ2, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(fName, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pass1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(43, 53, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lName)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Gender, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(jRadioButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(21, 21, 21))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(Countrylable)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Country, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(SecQlable)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(SecQ, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(emptyy, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(sendBut))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Birthlable)
                        .addGap(48, 48, 48)
                        .addComponent(Birth1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(jLabel3))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)
                                .addComponent(fName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pass1)
                            .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addComponent(pass))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3)
                    .addComponent(Gender))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Countrylable)
                    .addComponent(Country, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SecQlable)
                    .addComponent(SecQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(SecQ2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Birthlable)
                    .addComponent(Birth1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(emptyy, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sendBut))
                .addGap(63, 63, 63))
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(400, 10, 430, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 833, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sendButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendButActionPerformed
                    // TODO add your handling code here:       
       emptyy.setForeground(Color.red);
     if(fName.getText().isEmpty() || lName.getText().isEmpty() || Email.getText().isEmpty() || Password.getText().isEmpty() || 
              SecQ2.getText().isEmpty() || SecQ.getSelectedItem().equals("-Select-" ) || Country.getSelectedItem().equals("-Select-" ) || Birth1.isValid())
     {
            emptyy.setText("All fields are required");
    }else if(fName.getText().length()<3 || lName.getText().length()<3){
        emptyy.setText(" first name & last name must be more than 3 letters");
    } else if (Password .getText().toLowerCase().equals(Password.getText())){
        emptyy.setText(" password must contain capital letter");
    }
     else if (!Email .getText().contains("@")){
        emptyy.setText(" Please include an '@' in your email");
    }
      else if (buttonGroup1 .getSelection() == null ){
          emptyy.setText(" Please Choose Your Gender");
    }
        else if (Country.getSelectedItem().equals("-Select-" )){
          emptyy.setText(" Please Choose Your Country");
    }
      else if (SecQ.getSelectedItem().equals("-Select-" )){
          emptyy.setText(" Please Choose Your Secret Question");
    }
      else if (SecQ2.getText().isEmpty()){
          emptyy.setText(" Please Write The Answer About Secret Question");
    }
       else if (Birth1.isValid()){
          emptyy.setText(" Please Write Your Date of Birth");
    }
        
     else{
            sendBut.addActionListener(e->{
            jPanel3.setLayout(new CardLayout()); 
            jPanel3.removeAll();
            jPanel2.removeAll();
            jPanel3.add(new Login(Email.getText(), Password.getText(), fName.getText() , lName.getText() , 
                    SecQ2.getText(), SecQ.getSelectedItem().toString(),
                    Country.getSelectedItem().toString(),gen,Birth1.getDate().toString()));
            jPanel3.revalidate();
        });
    }
    }//GEN-LAST:event_sendButActionPerformed





    
    
    private void close(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_close
        int choice = JOptionPane.showConfirmDialog(this, "Are you want to exit?", "confirmation", JOptionPane.OK_CANCEL_OPTION,JOptionPane.INFORMATION_MESSAGE);
         if (choice == JOptionPane.YES_OPTION){
            System.exit(0);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_close

    private void hover(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hover
        // TODO add your handling code here:
        sendBut.setBackground(Color.gray);
    }//GEN-LAST:event_hover

    private void notHover(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_notHover
        // TODO add your handling code here:
                sendBut.setBackground(Color.lightGray);

    }//GEN-LAST:event_notHover

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        gen = "female";        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        gen = "male";        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void CountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CountryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CountryActionPerformed

    private void SecQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SecQActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SecQActionPerformed


    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser Birth1;
    private javax.swing.JLabel Birthlable;
    private javax.swing.JComboBox<String> Country;
    private javax.swing.JLabel Countrylable;
    private javax.swing.JTextField Email;
    private javax.swing.JLabel Gender;
    private javax.swing.JPasswordField Password;
    private javax.swing.JComboBox<String> SecQ;
    private javax.swing.JTextField SecQ2;
    private javax.swing.JLabel SecQlable;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel emptyy;
    private javax.swing.JTextField fName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JTextField lName;
    private javax.swing.JLabel pass;
    private javax.swing.JLabel pass1;
    private javax.swing.JLabel pass2;
    private javax.swing.JButton sendBut;
    // End of variables declaration//GEN-END:variables
}
